apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-pr-pipeline
  namespace: tekton-awl
spec:
  resources:
    - name: source
      type: git
  params:
  - name: revision
    type: string
    default: 42
  tasks:
    - name: github-set-status-start
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: awlauria/awlauria-tekton-demo
        - name: SHA
          value: "$(params.revision)"
        - name: DESCRIPTION
          value: "build started"
        - name: STATE
          value: pending
        - name: AUTH_TYPE
          value: Bearer
        - name: TARGET_URL
          value: https://api.github.com/repos/awlauria/awlauria-tekton-demo/statuses/$(params.revision)
    - name: test
      taskRef:
        name: test
      runAfter:
        - github-set-status-start
      resources:
        inputs:
        - name: source
          resource: source
    - name: github-set-status-end
      taskRef:
        name: github-set-status
      runAfter:
        - test
      params:
        - name: REPO_FULL_NAME
          value: awlauria/awlauria-tekton-demo
        - name: SHA
          value: "$(params.revision)"
        - name: DESCRIPTION
          value: "build complete"
        - name: STATE
          value: success
        - name: AUTH_TYPE
          value: Bearer
        - name: TARGET_URL
          value: https://api.github.com/repos/awlauria/awlauria-tekton-demo/statuses/$(params.revision)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
  namespace: tekton-awl
spec:
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: run-image
      image: awlauria/tekton-demo:latest
      imagePullPolicy: Always
      script: |
        #!/bin/bash
        cd /workspace/source
        ls -ltr
        cat hello_world.cpp
        g++ -g -o hello_world hello_world.cpp
        ./hello_world
        sleep 10
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  labels:
    tekton.dev/task: github-set-status
  name: github-set-status
  namespace: tekton-awl
spec:
  taskRef:
    kind: Task
    name: github-set-status-with-basic-auth
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mytaskrun
  namespace: tekton-awl
spec:
  taskRef:
    name: test
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
