apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: github-pr-pipeline
  namespace: tekton-awl
spec:
  resources:
    - name: source
      type: git
  params:
  - name: revision
    type: string
    default: 42
  tasks:
#    - name: github-set-status-start
#     taskRef:
#        name: github-set-status
#      params:
#        - name: REPO_FULL_NAME
#          value: awlauria/awlauria-tekton-demo
#        - name: SHA
#          value: "$(params.revision)"
#        - name: DESCRIPTION
#          value: "build started"
#        - name: STATE
#          value: pending
#        - name: AUTH_TYPE
#          value: Bearer
#        - name: TARGET_URL
#          value: http://localhost:9097/#/namespaces/tekton-awl/pipelineruns/github-run-$(params.revision)
    - name: test
      taskRef:
        name: test
#      runAfter:
#        - github-set-status-start
      resources:
        inputs:
        - name: source
          resource: source
#    - name: github-set-status-end
#      taskRef:
#        name: github-set-status
#      runAfter:
#        - test
#      params:
#        - name: REPO_FULL_NAME
#          value: awlauria/awlauria-tekton-demo
#        - name: SHA
#          value: "$(params.revision)"
#        - name: DESCRIPTION
#          value: "$(tasks.test.results.exit_string)"
#        - name: STATE
#          value: "$(tasks.test.results.exit_state)"
#        - name: AUTH_TYPE
#          value: Bearer
#        - name: TARGET_URL
#          value: http://localhost:9097/#/namespaces/tekton-awl/pipelineruns/github-run-$(params.revision)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test
  namespace: tekton-awl
spec:
  results:
    - name: exit_string
      description: Exit string of test
    - name: exit_state
      description: The exit state of the test (success/failure)
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: run-image
      image: awlauria/tekton-demo:latest
      imagePullPolicy: Always
      onError: continue
      script: |
        #!/bin/bash
        cd /workspace/source
        ls -ltr
        cat hello_world.cpp
        g++ -g -o hello_world hello_world.cpp
        out=$?
        echo $out
        if [[ $out -ne 0 ]] ;
        then
          echo -n "Test failed!" | tee $(results.exit_string.path)
          echo -n "failure" | tee $(results.exit_state.path)
          exit 1
        fi
        ./hello_world
        out=$?
        echo -n "success" | tee $(results.exit_state.path)
        echo -n "Test passed!" | tee $(results.exit_string.path)
#---
#apiVersion: tekton.dev/v1beta1
#kind: TaskRun
#metadata:
#  labels:
#    tekton.dev/task: github-set-status
#  name: github-set-status
#  namespace: tekton-awl
#spec:
#  taskRef:
#    kind: Task
#    name: github-set-status-with-basic-auth
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: mytaskrun
  namespace: tekton-awl
spec:
  taskRef:
    name: test
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
